# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    - script: 'mvn clean install'  # Build the Maven project
      displayName: 'Build with Maven'
      workingDirectory: $(System.DefaultWorkingDirectory)

- stage: Test
  jobs:
  - job: TestJob
    displayName: 'Run JUnit Tests'
    steps:
    - script: 'mvn test'  # Run JUnit tests using Maven
      displayName: 'Run JUnit Tests'
      workingDirectory: $(System.DefaultWorkingDirectory)